# Generated by Django 4.2.1 on 2023-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "partkey",
                    models.AutoField(
                        db_column="partKey", primary_key=True, serialize=False
                    ),
                ),
                ("department", models.CharField(max_length=20)),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
            ],
            options={"db_table": "part", "managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "personkey",
                    models.AutoField(
                        db_column="personKey", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
            ],
            options={"db_table": "user", "managed": False,},
        ),
    ]
