# Generated by Django 4.2.1 on 2023-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('cam_pk', models.AutoField(db_column='cam_PK', primary_key=True, serialize=False)),
                ('camimagepath', models.CharField(db_column='CAMimagePATH', max_length=100)),
                ('screentshortpath', models.CharField(db_column='ScreentShortPATH', max_length=100)),
                ('detectiontype', models.CharField(db_column='DetectionType', max_length=100)),
            ],
            options={
                'db_table': 'cam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_pk', models.AutoField(db_column='employee_PK', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcinfo',
            fields=[
                ('ip_pk', models.CharField(db_column='IP_PK', max_length=100, primary_key=True, serialize=False)),
                ('pcinfo', models.CharField(db_column='PCInfo', max_length=50)),
                ('userinfo', models.CharField(db_column='UserInfo', max_length=50)),
                ('macaddress', models.CharField(db_column='MACAddress', max_length=50)),
                ('dateinfo', models.DateTimeField(db_column='DateInfo')),
            ],
            options={
                'db_table': 'pcinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
