# Generated by Django 4.2.2 on 2023-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_no', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dection',
            fields=[
                ('dect_no', models.AutoField(primary_key=True, serialize=False)),
                ('cam_path', models.CharField(db_column='CAM_path', max_length=300)),
                ('screen_path', models.CharField(max_length=300)),
                ('detectiontype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depmt_no', models.AutoField(primary_key=True, serialize=False)),
                ('depmt_name', models.CharField(max_length=20)),
                ('landline', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=10)),
                ('emp_img_path', models.TextField()),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('ident_no', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(db_column='IP', max_length=100)),
                ('mac', models.CharField(db_column='MAC', max_length=100)),
            ],
            options={
                'db_table': 'identify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_no', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
