# Generated by Django 4.2.1 on 2023-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_no', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(db_column='IP', max_length=20)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('part_no_pk', models.AutoField(db_column='part_no_PK', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('mac_address_pk', models.CharField(db_column='MAC_Address_PK', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('employee_img_path', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('join_day', models.DateTimeField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_no_pk', models.AutoField(db_column='log_no_PK', primary_key=True, serialize=False)),
                ('camimage_path', models.TextField(db_column='CAMimage_path')),
                ('screenshot_path', models.TextField()),
                ('detectiontype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_no_pk', models.AutoField(db_column='report_no_PK', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
