# Generated by Django 4.2.2 on 2023-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dection',
            fields=[
                ('dect_no', models.AutoField(primary_key=True, serialize=False)),
                ('cam_path', models.CharField(db_column='CAM_path', max_length=300)),
                ('screen_path', models.CharField(max_length=300)),
                ('detectiontype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='identify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_column='IP', max_length=100)),
                ('mac', models.CharField(db_column='MAC', max_length=100)),
            ],
            options={
                'db_table': 'identify',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
